### ISSUE TITLE
Do more with less

### ISSUE THREAD

**Issue by lalligood** [learnbyexample/Command-line-text-processing#14]
First, I'm sorry for submitting a PR (#11) without reading the README more closely. Just wanted to contribute what I hope will be some useful knowledge to the project.

IMHO, `less` is a largely underutilized tool that can greatly improve upon, if not replace, the functionality of several other commands--namely `cat` & `tail`--as you'll see in my PR. Also `less` is a tool of convenience because how many times have you opened a file with it, then exited `less` to open it in your editor? Yet you can jump straight into your editor from within `less`! Lastly, you can view multiple files with `less` in a manner--and keystrokes--akin to changing buffers in vim.

**Comment by learnbyexample** [comment]
I added contributing guidelines to README only recently, long after you'd submitted PR..

not really sure if I want to add them, hence I left it as such.. probably should've at least commented to let you know my thoughts..

when I started this repo, I was mostly improving upon content I already put in https://github.com/learnbyexample/Linux_command_line repo.. in hindsight `less` doesn't belong much as cli text processing tool(as in other than viewing text) and could've been just a note in Text Editors section.. you can see that `tail -f` is not explained in this repo and some features of `cat` are given as further reading... imo, `cat/tail/less` serve very different purposes and are not meant as replacement for each other..

I'd suggest to open an issue in https://github.com/learnbyexample/Linux_command_line repo, discuss and then submit it as PR there...

**Comment by learnbyexample** [comment]
I'm no longer actively working on this repo.
