### ISSUE TITLE
Missing cat command

### ISSUE THREAD

**Issue by teeks99** [learnbyexample/Command-line-text-processing#17]
In gnu_sed.md around line 182, there should be an additional cat command that results in the output being shown.

This:

    # original file gets preserved in 'greeting.txt.bkp'
    Hi there
    Have a nice day

Should be this instead:

    # original file gets preserved in 'greeting.txt.bkp'
    $ cat greeting.txt.bkp
    Hi there
    Have a nice day

**Comment by learnbyexample** [comment]
thanks, corrected it...
