### ISSUE TITLE
Complex character class description as code

### ISSUE THREAD

**Issue by teeks99** [learnbyexample/Command-line-text-processing#18]
In gnu_grep.md (around line ) and gnu_sed.md (around line 1402) there is an example of equalivent word and space character classes. Unfortunately these are valid-ish markdown, and so do not get rendered correctly. They should be escaped as code in both places.

This: 

    | Character classes | Description |
    | ------------- | ----------- |
    | \w | Same as [0-9a-zA-Z_] or [[:alnum:]_] |
    | \W | Same as [^0-9a-zA-Z_] or [^[:alnum:]_] |
    | \s | Same as [[:space:]] |
    | \S | Same as [^[:space:]] |

Should be this:

    | Character classes | Description |
    | ------------- | ----------- |
    | `\w` | Same as `[0-9a-zA-Z_]` or `[[:alnum:]_]` |
    | `\W` | Same as `[^0-9a-zA-Z_]` or `[^[:alnum:]_]` |
    | `\s` | Same as `[[:space:]]` |
    | `\S` | Same as `[^[:space:]]` |

The ticks around the slash classes aren't necessary for formatting, but I think are good style (elsewhere in the document these are generally formatted as code).

For consistency and clarity, it might also make sense to apply this pattern to the table a couple paragraphs above this. I don't see any markdown issues there, but I think it would generally be clearer to list the actual regex patterns as code.

**Comment by learnbyexample** [comment]
>do not get rendered correctly

can you post a snapshot of what you are seeing?

I think I'd agree with you that showing these within backticks would be better for clarity..

**Comment by learnbyexample** [comment]
yeah, I've observed gitbook and github rendering not matching before... thanks for spotting and reporting this one..

I've changed it now
