### ISSUE TITLE
 cat -E marks_2015.txt  is not working

### ISSUE THREAD

**Issue by MohamedDiaa** [learnbyexample/Command-line-text-processing#19]
$ cat -E marks_2015.txt 
cat: illegal option -- E
usage: cat [-benstuv] [file ...]

**Comment by MohamedDiaa** [comment]
it works with small case options 
$ cat -e marks_2015.txt instead of $ cat -E marks_2015.txt

**Comment by learnbyexample** [comment]
that depends on your `cat` version.. I've mentioned in README that `GNU/Linux` has been used for examples presented.. usually, I add the version of command used at start of those sections, but I've missed it for this chapter.. thanks for bringing to attention..

from manual for `cat (GNU coreutils) 8.25`

>  -e     equivalent to -vE
> 
>  -v, --show-nonprinting
>      use ^ and M- notation, except for LFD and TAB
>
>  -E, --show-ends
>      display $ at end of each line
