### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by ss18** [learnbyexample/Command-line-text-processing#20]
perl_the_swiss_knife.md: dyas -> days
gnu_awk.md: intial -> initial
gnu_sed.md: whereever -> wherever
perl_the_swiss_knife.md: wtih -> with
Found with: https://github.com/ss18/grep-typos

**Comment by learnbyexample** [comment]
the `Perl` chapter ones are not actually typos, they are output of text mangled with `shuffle`

>Why coannt I go back to my inoagrnt dyas wtih wild imiaintangos and fatenasis?
