### ISSUE TITLE
Error in output

### ISSUE THREAD

**Issue by bwu62** [learnbyexample/Command-line-text-processing#21]
In section Filtering, subsection Fixed string matching, the command $ awk 'index($0,"a+b")' eqns.txt should return all lines of the input file, since a+b appears in each line, right?

**Comment by learnbyexample** [comment]
thanks a lot for spotting the issue..

I checked my local copy and seems like I had changed first line of input from `a+b=c` to `a-b=c` but forgot to change it in the sample shown.. that way, there will some lines matching and some not matching..

I'll change it..

**Comment by bwu62** [comment]
great response time, and thanks for the fix!
