### ISSUE TITLE
ex13_regex_character_class_part2 mismatch for question 1

### ISSUE THREAD

**Issue by pourradass** [learnbyexample/Command-line-text-processing#24]
Submitting my solution for question 1 of ex13_regex_character_class_part2 results in the below:

> Mismatch for question 1: 
> Expected output is:
> a[2]
> foo_bar
> appx_pi
> greeting
> food[4]
> b[0][1]

But it is the exact same output I'm getting. I've even tried with the solution from .ref_solutions, without any luck.

![image](https://user-images.githubusercontent.com/7921628/53686208-29224080-3d1c-11e9-8fc2-05a8798ae3fb.png)

Using GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)

**Comment by learnbyexample** [comment]
Thanks a lot for reporting this issue :+1:
Also, thanks for such a detailed error report, makes it very easy for me.

This was a corner case issue when command output contained a glob character, hence why it wasn't caught by me during manual testing (I need to create automatic testing for this script I suppose, at least for all the questions and answers in this repo)

I have fixed the [solve](https://github.com/learnbyexample/Command-line-text-processing/blob/master/exercises/GNU_grep/solve) script, can you check if it is working now for you?

**Comment by pourradass** [comment]
No worries and yes I can confirm the issue is now solved, thanks!
