### ISSUE TITLE
tr command

### ISSUE THREAD

**Issue by danliston** [learnbyexample/Command-line-text-processing#26]
Decoding your rot13 email address at the bottom of page 2 does not work in solaris, unless GNU utils are installed.  The string1 string2 patterns for tr in solaris are literal.

 rot13 code/decode that works with all versions of "tr" and handles both upper and lower case.
 the alias is wrapped in this text box but belongs all on the same line.
alias rot13="tr 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ' 'nopqrstuvwxyzabcdefghijklmNOPQRSTUVWXYZABCDEFGHIJKLM'"

Now you can simply pipe text to rot13.
echo 'yrneaolrknzcyr.arg@tznvy.pbz' | rot13

**Comment by learnbyexample** [comment]
Yeah, some commands/options work differently on different platforms, or the feature isn't available at all.

That's why the readme file has this note:

> Examples have been tested on GNU/Linux - there'd be syntax/feature variations with other distributions, consult their respective man pages for details.
