### ISSUE TITLE
Processing Fixed-Width Data

### ISSUE THREAD

**Issue by quobit** [learnbyexample/Command-line-text-processing#3]
Adding fixed-width data would be interesting: https://www.gnu.org/software/gawk/manual/html_node/Fixed-width-data.html#Fixed-width-data

**Comment by learnbyexample** [comment]
I did add a simple example - https://github.com/learnbyexample/Command-line-text-processing/blob/master/gnu_awk.md#fpat-and-fieldwidths
followed by links to more examples
will add the manual link as well, thanks

**Comment by learnbyexample** [comment]
added manual link as well
