### ISSUE TITLE
Add section for tee(1)

### ISSUE THREAD

**Issue by sector-f** [learnbyexample/Command-line-text-processing#5]
I think it would be a good idea to mention the `tee` command, probably somewhere in the "Cat, Less, Tail and Head" chapter

**Comment by iabhee** [comment]
Added Tee commands #6

**Comment by learnbyexample** [comment]
I feel `tee` command is more of [shell redirection](https://github.com/learnbyexample/Linux_command_line/blob/master/Shell.md#redirection) discussion, not really a text **processing** command...

thanks for suggestion anyway, leaving the issue open for now

**Comment by learnbyexample** [comment]
I'm no longer actively working on this repo.
