### ISSUE TITLE
Add pretty-print commands

### ISSUE THREAD

**Issue by KrumpetPirate** [learnbyexample/Command-line-text-processing#7]
XML: xmllint --format
JSON: cat $file | python -mjson.tool

That kind of thing might be useful for this collection.

**Comment by learnbyexample** [comment]
`Parsers for html, xml, csv, json, etc` is already part of `Possible additions` section

might add pretty print too, thanks for suggestion

**Comment by learnbyexample** [comment]
I'm no longer actively working on this repo.
